ALTER TABLE [dbo].[FIN_Asiento]
    ADD CONSTRAINT [PK_FIN_Asiento] PRIMARY KEY CLUSTERED ([IdAsiento] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

