ALTER TABLE [dbo].[FIN_Moneda]
    ADD CONSTRAINT [PK_FIN_Moneda] PRIMARY KEY CLUSTERED ([IdMoneda] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

