ALTER TABLE [dbo].[FIN_SaldoXCuentaXMoneda]
    ADD CONSTRAINT [PK_FIN_SaldoXCuentaXMoneda] PRIMARY KEY CLUSTERED ([IdCuenta] ASC, [IdMoneda] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

