ALTER TABLE [dbo].[FIN_HistorialTipoCambio]
    ADD CONSTRAINT [PK_FIN_HistorialTipoCambio] PRIMARY KEY CLUSTERED ([IdMonedaOrigen] ASC, [IdMonedaDestino] ASC, [Fecha] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

