ALTER TABLE [dbo].[FIN_Cuenta]
    ADD CONSTRAINT [PK_FIN_Cuenta] PRIMARY KEY CLUSTERED ([IdCuenta] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

