ALTER TABLE [dbo].[FIN_IdentificadorCuenta]
    ADD CONSTRAINT [PK_FIN_IdentificadorCuenta] PRIMARY KEY CLUSTERED ([IdidentificadorCuenta] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

