ALTER TABLE [dbo].[FIN_MontosXMonedaXAsientos]
    ADD CONSTRAINT [PK_FIN_MontosXMonedaXAsientos] PRIMARY KEY CLUSTERED ([IdAsiento] ASC, [IdCuenta] ASC, [IdMoneda] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

