ALTER TABLE [dbo].[FIN_CuentasXAsiento]
    ADD CONSTRAINT [PK_FIN_CuentasXAsiento] PRIMARY KEY CLUSTERED ([IdAsiento] ASC, [IdCuenta] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

