ALTER TABLE [dbo].[FIN_EstadoMes]
    ADD CONSTRAINT [PK_FIN_EstadoMes] PRIMARY KEY CLUSTERED ([IdEstadoMes] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

