ALTER TABLE [dbo].[ERP_ContactoXEntidad]
    ADD CONSTRAINT [PK_ERP_ContactoXEntidad] PRIMARY KEY CLUSTERED ([IdEntidad] ASC, [IdContacto] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

