ALTER TABLE [dbo].[ERP_Paises]
    ADD CONSTRAINT [PK_ERP_Paises] PRIMARY KEY CLUSTERED ([IdPais] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

