ALTER TABLE [dbo].[ERP_Entidades]
    ADD CONSTRAINT [PK_ERP_Entidades] PRIMARY KEY CLUSTERED ([IdEntidad] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

