ALTER TABLE [dbo].[ERP_EntidadXPais]
    ADD CONSTRAINT [PK_ERP_EntidadXPais] PRIMARY KEY CLUSTERED ([IdEntidad] ASC, [IdPais] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

