ALTER TABLE [dbo].[ERP_TipoUsuario]
    ADD CONSTRAINT [PK_ERP_TipoUsuario] PRIMARY KEY CLUSTERED ([IdTipoUsuario] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

