ALTER TABLE [dbo].[ERP_Contacto]
    ADD CONSTRAINT [PK_ERP_Contacto] PRIMARY KEY CLUSTERED ([IdContacto] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

