ALTER TABLE [dbo].[ERP_Permisos]
    ADD CONSTRAINT [PK_ERP_Permisos] PRIMARY KEY CLUSTERED ([IdPermisos] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

