ALTER TABLE [dbo].[ERP_Usuarios]
    ADD CONSTRAINT [PK_ERP_Usuarios] PRIMARY KEY CLUSTERED ([IdUsuario] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

