ALTER TABLE [dbo].[ERP_UsuarioXModulo]
    ADD CONSTRAINT [PK_ERP_UsuarioXModulo] PRIMARY KEY CLUSTERED ([IdModulo] ASC, [IdUsuario] ASC, [IdTipoUsuario] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

