ALTER TABLE [dbo].[ERP_PermisosXTipoUsuario]
    ADD CONSTRAINT [PK_ERP_PermisosXTipoUsuario] PRIMARY KEY CLUSTERED ([IdPermisos] ASC, [IdTipoUsuario] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

