ALTER TABLE [dbo].[ERP_Modulos]
    ADD CONSTRAINT [PK_ERP_Modulos] PRIMARY KEY CLUSTERED ([IdModulo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

