ALTER TABLE [dbo].[ArticuloXBodega]
    ADD CONSTRAINT [PK_ArticuloXBodega] PRIMARY KEY CLUSTERED ([IdArticulo] ASC, [IdBodega] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

