ALTER TABLE [dbo].[ArticulosXDetalle]
    ADD CONSTRAINT [PK_ArticulosXDetalle] PRIMARY KEY CLUSTERED ([IdArticulo] ASC, [IdDetalle] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

