ALTER TABLE [dbo].[Bodega]
    ADD CONSTRAINT [PK_Bodega] PRIMARY KEY CLUSTERED ([IdBodega] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

