ALTER TABLE [dbo].[DetalleServicios]
    ADD CONSTRAINT [PK_DetalleServicios] PRIMARY KEY CLUSTERED ([IdDetalleServicios] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

