ALTER TABLE [dbo].[DetalleDocumento]
    ADD CONSTRAINT [PK_DetalleDocumento] PRIMARY KEY CLUSTERED ([IdDetalle] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

