ALTER TABLE [dbo].[EncabezadoDocumento]
    ADD CONSTRAINT [PK_EncabezadoDocumento] PRIMARY KEY CLUSTERED ([IdEncabezado] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

