ALTER TABLE [dbo].[FotografiaXArticulo]
    ADD CONSTRAINT [PK_FotografiaXArticulo] PRIMARY KEY CLUSTERED ([IdFotografia] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

