ALTER TABLE [dbo].[SocioNegocio]
    ADD CONSTRAINT [PK_SocioNegocio] PRIMARY KEY CLUSTERED ([IdSocioNegocio] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

