ALTER TABLE [dbo].[Transferencia]
    ADD CONSTRAINT [PK_Transferencia] PRIMARY KEY CLUSTERED ([IdTransferencia] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

