ALTER TABLE [dbo].[TipoSocioNegocio]
    ADD CONSTRAINT [PK_TipoSocioNegocio] PRIMARY KEY CLUSTERED ([IdTipoSocio] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

