ALTER TABLE [dbo].[TipoTransferencia]
    ADD CONSTRAINT [PK_TipoTransferencia] PRIMARY KEY CLUSTERED ([IdTipoTransferencia] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

