ALTER TABLE [dbo].[UnidadMedida]
    ADD CONSTRAINT [PK_UnidadMedida] PRIMARY KEY CLUSTERED ([IdUnidadMedida] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

